[package]
name = "rust_book_api"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "rust_book_api"
path = "src/main.rs"